# see: https://golangci-lint.run/usage/configuration/

run:
  tests: true

issues:
  exclude-use-default: false

linters:
  enable:
    - godox
    - goimports
    - golint
    - gosec
    - noctx
    - nolintlint
    - prealloc
    - misspell

